openapi: 3.0.1
info:
  title: apra-rag
  version: 1.0.0
paths:
  /rag_search:
    post:
      operationId: ragSearch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                topK:
                  type: integer
                  default: 5
                filters:
                  type: object
                conversationId:
                  type: string
      responses:
        "200":
          description: OK
