"""Parallel retrieval orchestration for query decomposition sub-questions."""

from __future__ import annotations

import asyncio
import logging
from typing import Any

from .models import RetrieveRequest
from .repository import PostgresRepository

logger = logging.getLogger(__name__)


class DecompositionRetriever:
    """Orchestrates parallel retrieval for sub-questions generated by query decomposition."""

    def __init__(self, repository: PostgresRepository):
        """Initialize with repository for retrieval operations.

        Args:
            repository: PostgresRepository instance for hybrid retrieval
        """
        self._repository = repository

    async def retrieve_sub_questions_parallel(
        self,
        sub_questions: list[str],
        base_request: RetrieveRequest,
        timeout_seconds: int = 30,
    ) -> list[list[dict[str, Any]]]:
        """Retrieve documents for each sub-question in parallel using asyncio.

        Uses asyncio.gather to fan-out parallel retrieval tasks.
        Each sub-question is retrieved with the same top_k/filters as base_request.

        Args:
            sub_questions: List of sub-question strings
            base_request: Base RetrieveRequest to clone for each sub-question
            timeout_seconds: Timeout per sub-question retrieval

        Returns:
            List of hit lists, one per sub-question. Empty list on per-query failures.

        Raises:
            asyncio.TimeoutError: If overall operation exceeds timeout
        """
        if not sub_questions:
            logger.warning("retrieve_sub_questions_parallel: no sub-questions provided")
            return []

        try:
            tasks = [
                self._retrieve_single_sub_question(
                    sub_q, base_request, timeout_seconds
                )
                for sub_q in sub_questions
            ]

            results = await asyncio.gather(*tasks, return_exceptions=True)

            # Process results, converting exceptions to empty lists
            processed_results = []
            for i, result in enumerate(results):
                if isinstance(result, Exception):
                    logger.warning(
                        "Sub-question [%d] retrieval failed: %s",
                        i,
                        result,
                    )
                    processed_results.append([])
                else:
                    processed_results.append(result)

            logger.info(
                "Retrieved results for %d sub-questions (timeouts/errors handled)",
                len(processed_results),
            )
            return processed_results

        except Exception as e:
            logger.exception("retrieve_sub_questions_parallel failed: %s", e)
            return []

    async def _retrieve_single_sub_question(
        self,
        sub_question: str,
        base_request: RetrieveRequest,
        timeout_seconds: int,
    ) -> list[dict[str, Any]]:
        """Retrieve documents for a single sub-question (async wrapper).

        Args:
            sub_question: Sub-question string
            base_request: Base request to clone
            timeout_seconds: Timeout for this retrieval

        Returns:
            List of hits for this sub-question

        Raises:
            asyncio.TimeoutError: If retrieval exceeds timeout
            Exception: On retrieval failures
        """
        try:
            loop = asyncio.get_event_loop()

            # Create a cloned request with the sub-question as query
            sub_request = RetrieveRequest(
                query=sub_question,
                k_sparse=base_request.k_sparse,
                k_dense=base_request.k_dense,
                k_final=base_request.k_final,
                filters=base_request.filters,
                query_embedding=base_request.query_embedding,  # Reuse parent embedding
            )

            # Run blocking retrieve in thread pool
            hits = await asyncio.wait_for(
                loop.run_in_executor(
                    None,
                    self._repository.retrieve,
                    sub_request,
                ),
                timeout=timeout_seconds,
            )

            logger.debug(
                "Sub-question retrieval succeeded: query=%r, hits=%d",
                sub_question[:60],
                len(hits),
            )
            return hits

        except asyncio.TimeoutError:
            logger.warning(
                "Sub-question retrieval timeout: query=%r (timeout_s=%d)",
                sub_question[:60],
                timeout_seconds,
            )
            raise
        except Exception as e:
            logger.warning(
                "Sub-question retrieval failed: query=%r, error=%s",
                sub_question[:60],
                e,
            )
            raise

    def retrieve_sub_questions_sequential(
        self,
        sub_questions: list[str],
        base_request: RetrieveRequest,
    ) -> list[list[dict[str, Any]]]:
        """Retrieve documents for each sub-question sequentially (sync fallback).

        Used when async context is not available.

        Args:
            sub_questions: List of sub-question strings
            base_request: Base RetrieveRequest to clone for each sub-question

        Returns:
            List of hit lists, one per sub-question. Empty list on failures.
        """
        if not sub_questions:
            logger.warning(
                "retrieve_sub_questions_sequential: no sub-questions provided"
            )
            return []

        results = []
        for i, sub_q in enumerate(sub_questions):
            try:
                sub_request = RetrieveRequest(
                    query=sub_q,
                    k_sparse=base_request.k_sparse,
                    k_dense=base_request.k_dense,
                    k_final=base_request.k_final,
                    filters=base_request.filters,
                    query_embedding=base_request.query_embedding,
                )
                hits = self._repository.retrieve(sub_request)
                logger.debug(
                    "Sub-question [%d] retrieval: query=%r, hits=%d",
                    i,
                    sub_q[:60],
                    len(hits),
                )
                results.append(hits)
            except Exception as e:
                logger.warning(
                    "Sub-question [%d] retrieval failed: query=%r, error=%s",
                    i,
                    sub_q[:60],
                    e,
                )
                results.append([])

        logger.info("Sequential retrieval completed for %d sub-questions", len(results))
        return results

    @staticmethod
    def merge_sub_question_hits(
        original_hits: list[dict[str, Any]],
        sub_question_hits_list: list[list[dict[str, Any]]],
        original_weight: float = 1.0,
        sub_question_weight: float = 0.5,
        k_final: int = 10,
    ) -> list[dict[str, Any]]:
        """Merge original query hits with sub-question hits using weighted RRF.

        Strategy:
        - Original query hits get weight 1.0 (primary)
        - Each sub-question hit gets weight 0.5 (secondary)
        - Merge using reciprocal rank fusion
        - Return top k_final hits

        Args:
            original_hits: Hits from original query
            sub_question_hits_list: List of hit lists from sub-questions
            original_weight: Weight for original hits in RRF (default 1.0)
            sub_question_weight: Weight per sub-question hit (default 0.5)
            k_final: Final number of hits to return

        Returns:
            Merged and deduplicated top-k hits
        """
        if not original_hits and not sub_question_hits_list:
            logger.warning("merge_sub_question_hits: no hits to merge")
            return []

        # Build RRF score map: chunk_id -> score
        rrf_scores = {}

        # Add original hits with weight 1.0
        for rank, hit in enumerate(original_hits, start=1):
            chunk_id = hit.get("chunk_id") or hit.get("id", f"chunk_{rank}")
            rrf_scores[chunk_id] = rrf_scores.get(chunk_id, 0) + (
                original_weight / (1 + rank)
            )

        # Add sub-question hits with weight 0.5 each
        for sub_q_idx, sub_hits in enumerate(sub_question_hits_list):
            for rank, hit in enumerate(sub_hits, start=1):
                chunk_id = hit.get("chunk_id") or hit.get("id", f"chunk_sub_{sub_q_idx}_{rank}")
                rrf_scores[chunk_id] = rrf_scores.get(chunk_id, 0) + (
                    sub_question_weight / (1 + rank)
                )

        # Rebuild hit map for deduplication
        hit_map = {}
        for hit in original_hits:
            chunk_id = hit.get("chunk_id") or hit.get("id")
            if chunk_id:
                hit_map[chunk_id] = hit

        for sub_hits in sub_question_hits_list:
            for hit in sub_hits:
                chunk_id = hit.get("chunk_id") or hit.get("id")
                if chunk_id and chunk_id not in hit_map:
                    hit_map[chunk_id] = hit

        # Sort by RRF score and return top k_final
        sorted_chunk_ids = sorted(
            rrf_scores.keys(), key=lambda cid: rrf_scores[cid], reverse=True
        )
        merged_hits = [
            hit_map[cid] for cid in sorted_chunk_ids[:k_final] if cid in hit_map
        ]

        logger.info(
            "Merged %d original + %d sub-question hits → %d final hits",
            len(original_hits),
            sum(len(h) for h in sub_question_hits_list),
            len(merged_hits),
        )
        return merged_hits
